# Base image
FROM openjdk:11-jre-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the compiled Java application JAR file to the container
COPY target/product-0.0.1-SNAPSHOT.jar /app/app.jar

# Define the command to run when the container starts
CMD ["java", "-jar", "app.jar"]
